"use client";

import { useState, useEffect } from "react";
import { HOW_IT_WORKS_STEPS } from "@/constants/steps";
import type { StepArtType } from "@/types";

function StepArt({ art }: { art: StepArtType }) {
  const artBase: React.CSSProperties = {
    border: "1px solid var(--line)",
    borderRadius: 12,
    background: "var(--bg-0)",
    minHeight: 220,
    padding: 24,
    position: "relative",
    overflow: "hidden",
  };

  if (art === "doc") {
    return (
      <div style={{ ...artBase, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 }}>
        {[
          { title: "Discovery brief", items: ['Problem · "reconciliation takes 4 days/mo"', "Users · 3 finance ops, 1 CFO viewer", "Scope · upload + match + export", "Non-goals · multi-currency (v2)"] },
          { title: "Risk register", items: ["SOX evidence — confirm w/ auditor", "SFTP from bank — needs 2 weeks", "PII column — encrypt at rest", "Match logic — ML or rules?"] },
        ].map((col) => (
          <div key={col.title} style={{ fontFamily: "var(--font-mono)", fontSize: "11.5px", lineHeight: 1.8, color: "var(--fg-dim)" }}>
            <div style={{ color: "var(--accent)", fontSize: 10, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 8 }}>{col.title}</div>
            {col.items.map((item) => (
              <div key={item} style={{ display: "flex", gap: 10 }}>
                <span style={{ color: "var(--fg-faint)" }}>—</span>{item}
              </div>
            ))}
          </div>
        ))}
      </div>
    );
  }

  if (art === "flow") {
    return (
      <div style={{ ...artBase, display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, alignItems: "stretch" }}>
        {[
          { nm: "/login", desc: "2 fields · SSO · forgot" },
          { nm: "/dashboard", desc: "4 cards · 1 chart · filter" },
          { nm: "/upload", desc: "drag-drop · preview · validate" },
          { nm: "/export", desc: "csv · pdf · scheduled" },
        ].map((node, i) => (
          <div
            key={node.nm}
            style={{
              border: "1px solid var(--line)",
              borderRadius: 8,
              padding: 12,
              fontFamily: "var(--font-mono)",
              fontSize: 11,
              color: "var(--fg-dim)",
              background: "var(--bg-1)",
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between",
              position: "relative",
            }}
          >
            {i > 0 && <span style={{ position: "absolute", left: -16, top: "50%", transform: "translateY(-50%)", color: "var(--fg-faint)", fontSize: 14 }}>→</span>}
            <span style={{ color: "var(--accent)", fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase" }}>{node.nm}</span>
            <span>{node.desc}</span>
          </div>
        ))}
      </div>
    );
  }

  if (art === "arch") {
    const layers = [
      { lbl: "Edge", vals: "Next.js / Vercel · ISR · 12 routes" },
      { lbl: "API", vals: "tRPC · Zod · 38 procedures" },
      { lbl: "Data", vals: "Postgres (RLS) · Redis · S3" },
      { lbl: "AI", vals: "Claude · Haiku-routed · 2¢/req" },
      { lbl: "Ops", vals: "Vercel · Sentry · Datadog · PagerDuty" },
    ];
    return (
      <div style={{ ...artBase, display: "grid", gap: 12 }}>
        {layers.map((l) => (
          <div key={l.lbl} style={{ display: "grid", gridTemplateColumns: "100px 1fr", gap: 16, alignItems: "center", padding: "12px 16px", border: "1px solid var(--line)", borderRadius: 8, background: "var(--bg-1)", fontFamily: "var(--font-mono)", fontSize: 12 }}>
            <span style={{ color: "var(--accent)", fontSize: 10, letterSpacing: "0.12em", textTransform: "uppercase" }}>{l.lbl}</span>
            <span style={{ color: "var(--fg-dim)" }}>{l.vals}</span>
          </div>
        ))}
      </div>
    );
  }

  if (art === "code") {
    return (
      <div style={{ ...artBase }}>
        <pre style={{ fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.65, color: "var(--fg-dim)", margin: 0, whiteSpace: "pre-wrap" }}>
          <span style={{ color: "var(--fg-faint)", fontStyle: "italic" }}>{"// generated by claude-code · reviewed by @sarah\n"}</span>
          <span style={{ color: "#ff8050" }}>{"export async function "}</span>
          <span style={{ color: "#c5a3ff" }}>{"reconcile"}</span>{"(rows: Row[]) {\n"}
          {"  "}<span style={{ color: "#ff8050" }}>{"const "}</span>{"matched = "}<span style={{ color: "#ff8050" }}>{"await "}</span>{"matchAgainstLedger(rows);\n"}
          {"  "}<span style={{ color: "#ff8050" }}>{"const "}</span>{"{ ok, conflicts } = "}<span style={{ color: "#c5a3ff" }}>{"partition"}</span>{"(matched);\n"}
          {"  "}<span style={{ color: "#ff8050" }}>{"if "}</span>{"(conflicts.length > 0) {\n"}
          {"    "}<span style={{ color: "#ff8050" }}>{"await "}</span>{"flagForReview(conflicts);\n"}
          {"  }\n"}
          {"  "}<span style={{ color: "#ff8050" }}>{"return "}</span>{"{ matched: ok.length, flagged: conflicts.length };\n"}
          {"}\n"}
          <span style={{ color: "var(--fg-faint)", fontStyle: "italic" }}>{"// ✓ 12 tests · ✓ types · ✓ no security issues"}</span>
        </pre>
      </div>
    );
  }

  if (art === "qa") {
    const tests = [
      { name: "login.spec.ts", ms: "312ms", status: "ok" },
      { name: "upload-csv.spec.ts", ms: "1.2s", status: "ok" },
      { name: "a11y/contrast.spec.ts", ms: "patched", status: "warn" },
      { name: "match-engine.test.ts", ms: "88ms", status: "ok" },
      { name: "e2e/checkout.spec.ts", ms: "3.4s", status: "ok" },
      { name: "load/500rps.spec.ts", ms: "p99 142ms", status: "ok" },
      { name: "browser/safari.spec.ts", ms: "ok", status: "ok" },
      { name: "browser/firefox.spec.ts", ms: "ok", status: "ok" },
    ];
    return (
      <div style={{ ...artBase, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 }}>
        {[tests.slice(0, 4), tests.slice(4)].map((group, gi) => (
          <div key={gi} style={{ display: "flex", flexDirection: "column", gap: 10, fontFamily: "var(--font-mono)", fontSize: 12 }}>
            {group.map((t) => (
              <div key={t.name} style={{ display: "grid", gridTemplateColumns: "18px 1fr auto", gap: 10, alignItems: "center", padding: "8px 12px", border: "1px solid var(--line)", borderRadius: 8, background: "var(--bg-1)" }}>
                <span style={{ width: 8, height: 8, borderRadius: "50%", background: t.status === "ok" ? "var(--good)" : "#ffd166", display: "block", justifySelf: "center" }} />
                <span style={{ color: "var(--fg)" }}>{t.name}</span>
                <span style={{ color: "var(--fg-faint)", fontSize: 11 }}>{t.ms}</span>
              </div>
            ))}
          </div>
        ))}
      </div>
    );
  }

  if (art === "deploy") {
    const row1 = ["commit", "tests", "review", "staging", "prod"];
    const row2 = ["runbook", "hand-off", "training", "warranty", "retainer"];
    return (
      <div style={{ ...artBase, display: "grid", gap: 14 }}>
        {[row1, row2].map((row, ri) => (
          <div key={ri} style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", alignItems: "center", gap: 4, padding: 16, background: "var(--bg-1)", border: "1px solid var(--line)", borderRadius: 10, fontFamily: "var(--font-mono)", fontSize: 11 }}>
            {row.map((pt, i) => {
              const isPending = ri === 1 && i >= 3;
              return (
                <span key={pt} style={{ position: "relative", textAlign: "center", color: "var(--fg-dim)", paddingTop: 26 }}>
                  <span style={{ position: "absolute", top: 6, left: "50%", transform: "translateX(-50%)", width: 10, height: 10, borderRadius: "50%", background: isPending ? "var(--bg-3)" : "var(--good)", boxShadow: isPending ? "none" : "0 0 10px rgba(124,245,196,0.5)", display: "block" }} />
                  {i > 0 && <span style={{ position: "absolute", left: "-50%", right: "50%", top: 10, height: 1, background: isPending ? "var(--line)" : "var(--good)", display: "block" }} />}
                  {pt}
                </span>
              );
            })}
          </div>
        ))}
      </div>
    );
  }

  return null;
}

export function HowItWorks() {
  const [active, setActive] = useState(0);
  const [auto, setAuto] = useState(true);

  useEffect(() => {
    if (!auto) return;
    const id = setInterval(() => setActive((a) => (a + 1) % HOW_IT_WORKS_STEPS.length), 7000);
    return () => clearInterval(id);
  }, [auto]);

  const step = HOW_IT_WORKS_STEPS[active];

  return (
    <div
      className="steps-shell"
      style={{
        display: "grid",
        gridTemplateColumns: "280px 1fr",
        gap: 0,
        border: "1px solid var(--line)",
        borderRadius: "var(--radius-lg)",
        background: "var(--bg-1)",
        overflow: "hidden",
        minHeight: 540,
      }}
    >
      {/* Step list */}
      <div
        role="tablist"
        style={{
          borderRight: "1px solid var(--line)",
          padding: 12,
          display: "flex",
          flexDirection: "column",
        }}
        className="steps-list"
      >
        {HOW_IT_WORKS_STEPS.map((s, i) => {
          const isActive = i === active;
          return (
            <button
              key={s.key}
              role="tab"
              aria-selected={isActive}
              onClick={() => { setActive(i); setAuto(false); }}
              style={{
                textAlign: "left",
                background: isActive ? "var(--bg-2)" : "transparent",
                border: `1px solid ${isActive ? "var(--line)" : "transparent"}`,
                padding: "14px 14px",
                borderRadius: 10,
                color: isActive ? "var(--fg)" : "var(--fg-dim)",
                display: "grid",
                gridTemplateColumns: "28px 1fr",
                gap: 12,
                alignItems: "center",
                transition: "all 0.15s",
                fontSize: 14,
                width: "100%",
                cursor: "pointer",
              }}
            >
              <span
                style={{
                  fontFamily: "var(--font-mono)",
                  fontSize: 11,
                  color: isActive ? "#0a0a0a" : "var(--fg-faint)",
                  width: 28,
                  height: 28,
                  border: `1px solid ${isActive ? "var(--accent)" : "var(--line)"}`,
                  borderRadius: 6,
                  background: isActive ? "var(--accent)" : "transparent",
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                {String(i + 1).padStart(2, "0")}
              </span>
              <span>
                <span style={{ display: "block" }}>{s.label}</span>
                <span style={{ display: "block", fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--fg-faint)", marginTop: 2 }}>{s.sub}</span>
              </span>
            </button>
          );
        })}
      </div>

      {/* Step detail */}
      <div
        key={step.key}
        style={{ padding: 40, display: "grid", gridTemplateRows: "auto 1fr auto", gap: 24 }}
      >
        <h3 style={{ fontSize: 32, maxWidth: "22ch", letterSpacing: "-0.02em" }}>{step.title}</h3>
        <StepArt art={step.art} />
        <div>
          <p style={{ color: "var(--fg-dim)", maxWidth: "60ch", lineHeight: 1.65 }}>{step.desc}</p>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 16 }}>
            {step.meta.map((m) => (
              <span key={m} className="tag">{m}</span>
            ))}
          </div>
        </div>
      </div>

      <style>{`
        @media (max-width: 900px) {
          .steps-shell { grid-template-columns: 1fr !important; min-height: 0 !important; }
          .steps-list { border-right: 0 !important; border-bottom: 1px solid var(--line); flex-direction: row !important; overflow-x: auto; }
        }
      `}</style>
    </div>
  );
}
